"""add_is_default_to_users

Revision ID: b1d671e55087
Revises: 34e9591e092e
Create Date: 2026-09-28 19:57:20.486969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d671e55087'
down_revision: Union[str, Sequence[str], None] = '34e9591e092e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # If DEFAULT_USER_ID already exists, set its is_default = true
    op.execute("UPDATE users SET is_default = true WHERE id = '00000000-0000-0000-0000-000000000001'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_default')
    # ### end Alembic commands ###
